### PR TITLE
feat(language guesser model): created language guesser model and requ…

### LINKED ISSUE #20: Language Guesser
Code figures out what language is being used

### PR DESCRIPTION
**Pull request by Dawie0**
…ired function in main file

## Changes
_List Changes Introduced by this PR_
1. Added languageGuesserModel.js to utils folder
2. Created function to guess language of the param in string form
3. used module export and required function to main.js

## Purpose
_To get the language of text_

## Approach
_How does this change address the problem?_

## Learning
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

_If this closes an issue, reference the issue here. If it doesn't, remove this line_
Closes #20

### CODE REVIEW

**Review by Ernest0G — APPROVED** [review]
(praise): Looks good

**Review by tkgonzal — COMMENTED** [review]
(praise): Looks good !

**Review by missile720 — APPROVED** [review]
(praise): Looks good!

**Review by tkgonzal — APPROVED** [review]
(praise): Looks good !

**Pull request merged**
